#!/usr/bin/env python

from rootpy.extern.argparse import ArgumentParser
from rootpy.io import root_open
import numpy as np
import pickle

parser = ArgumentParser()
parser.add_argument('-o', '--output', default='bootstrap.pickle')
parser.add_argument('files', nargs='+')
args = parser.parse_args()

params = {}
# peak at first file to get parameters
with root_open(args.files[0]) as rfile:
    for ana in ('MVA', 'CBA'):
        print "Analysis: {0}".format(ana)
        ana_params = {}
        result = rfile[ana]
        for param in result.final_params:
            print param.name
            ana_params[param.name] = np.empty(len(args.files))
        print
        params[ana] = ana_params

for idx, file in enumerate(args.files):
    print "Processing {0} ...".format(file)
    with root_open(file) as rfile:
        for ana in ('MVA', 'CBA'):
            ana_params = params[ana]
            result = rfile[ana]
            for param in result.final_params:
                ana_params[param.name][idx] = param.value

pickle.dump(params, open(args.output, 'w'))
print "Done"
