#!/usr/bin/env python

"""
Check for duplicate events or invalid values (NaN, inf)
in all trees in a ROOT file.
"""
from rootpy.extern.argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('files', nargs='+')
args = parser.parse_args()

import sys
import os
from rootpy.io import root_open
import numpy as np
from root_numpy import RootNumpyUnconvertibleWarning
import warnings


warnings.simplefilter("ignore",
    RootNumpyUnconvertibleWarning)


def dup_idx(l):
    """
    Return the indices of all duplicated array elements
    I am very proud of this epic kung fu
    I promise to document it someday :)
    """
    _, b = np.unique(l, return_inverse=True)
    return np.nonzero(np.logical_or.reduce(
                b[:, np.newaxis] == np.nonzero(np.bincount(b) > 1),
                axis=1))[0]


def check_nan_inf(rec):

    for field in rec.dtype.names:
        if np.isnan(np.sum(rec[field])):
            print "invalid values for field %s" % field


for i, filename in enumerate(args.files):
    print filename
    with root_open(filename) as rfile:
        for dirpath, dirs, treenames in rfile.walk(class_pattern='TTree'):
            for treename in treenames:
                tree = rfile.Get(os.path.join(dirpath, treename))
                keys = tree.to_array(['RunNumber', 'EventNumber'])
                if keys.shape != np.unique(keys).shape:
                    print "BAD  %s" % treename
                    print dup_idx(keys)
                else:
                    print "GOOD %s" % treename
                check_nan_inf(tree.to_array())

    if i < len(args.files) - 1:
        # not the last file, print a blank line
        print
