#!/usr/bin/env python

from rootpy.extern.argparse import ArgumentParser
parser = ArgumentParser()
parser.add_argument('-f', '--fields', nargs='+', required=True)
parser.add_argument('filename')
args = parser.parse_args()

import rootpy
rootpy.log.basic_config_colorized()
from rootpy.io import root_open
from rootpy import log
import os

with root_open(args.filename) as fin:
    for dirpath, dirs, treenames in fin.walk(class_pattern='TTree'):
        for treename in treenames:
            treepath = os.path.join(dirpath, treename)
            intree = fin.Get(treepath)
            for field in args.fields:
                if not intree.has_branch(field):
                    log.warning("missing branch {0} in tree {1}".format(
                        field,
                        treepath))
