#!/usr/bin/env python

from mva.analysis import Analysis
from mva.samples import Higgs
from mva.categories import Category_VBF, Category_Boosted
from mva.defaults import TARGET_REGION
from mva.plotting import draw_ratio
from rootpy.plotting import Hist
from root_numpy import fill_hist

# begin configuration
modes = [
    'gg',
    'VBF',
]
ggf_weight = True
# end configuration

higgs = Higgs(2012, mass=125, modes=modes, ggf_weight=ggf_weight)
higgs_bch = Higgs(2012, mass=125, modes=modes, ggf_weight=ggf_weight,
                  student='hhskim_BCH',
                  suffix='_BCH.mc12b')

print "default raw number of events", higgs.events(weighted=False)[1].value
print "BCH-fixed sample raw number of events", higgs_bch.events(weighted=False)[1].value

FAIL_BCH_TIGHT = {
    Category_VBF: '!tau1_BCHTight&&!tau2_BCHTight&&!jet1_BCHTight&&!jet2_BCHTight',
    Category_Boosted: '!tau1_BCHTight&&!tau2_BCHTight',
}

analysis = Analysis(2012)

for category in (Category_VBF, Category_Boosted):
    # get the BDTs
    clf = analysis.get_clf(category, mass=125, load=True)
    # get scores
    scores, weights = higgs.scores(
        clf, category, TARGET_REGION,
        systematics=False)['NOMINAL']
    scores_bch, weights_bch = higgs_bch.scores(
        clf, category, TARGET_REGION,
        systematics=False)['NOMINAL']
    # get scores range
    min_score = min(scores.min(), scores_bch.min())
    max_score = max(scores.max(), scores_bch.max())
    # histograms
    hist = Hist(20, min_score - 1E-5, max_score + 1E-5, title='H 125 GeV')
    hist_bch = Hist(20, min_score - 1E-5, max_score + 1E-5, title='H 125 GeV with BCH fix')
    # fill histograms with scores
    fill_hist(hist, scores, weights)
    fill_hist(hist_bch, scores_bch, weights_bch)
    # plot the scores
    plot = draw_ratio(hist, hist_bch, 'BDT Score', category, normalize=False)
    plot.SaveAs('bch_compare_{0}.png'.format(category.name))
    
    print
    print "[N(r5470, no cuts) - N(default, no cuts)] / N(default, no cuts)"
    diff = (higgs_bch.events(category, TARGET_REGION)[1].value -
            higgs.events(category, TARGET_REGION)[1].value) / higgs.events(category, TARGET_REGION)[1].value
    print category.name, diff
    print

    print "[N(r5470, fail tight BCH-cut) - N(default, fail tight BCH-cut)] / N(default, no cuts)"
    diff = (higgs_bch.events(category, TARGET_REGION, cuts=FAIL_BCH_TIGHT[category])[1].value -
            higgs.events(category, TARGET_REGION, cuts=FAIL_BCH_TIGHT[category])[1].value) / higgs.events(category, TARGET_REGION)[1].value
    print category.name, diff 
    print
    print '-' * 20
