#!/usr/bin/env python
"""
"""
# python imports
import os
import logging
# ROOT/rootpy imports
from rootpy.tree import Cut
from rootpy.plotting import Canvas, Legend
# local imports
from mva.samples import Higgs
from mva.categories import Category_VBF, Category_Boosted
from mva.defaults import TARGET_REGION
from mva.variables import VARIABLES
from mva.plotting.templates import SimplePlot

log = logging.getLogger(os.path.basename(__file__))

def plot(hist_vbf, hist_boosted):
    hist_vbf.color = 'red'
    hist_boosted.color = 'blue'
    hist_vbf.legendstyle = 'f'
    hist_boosted.legendstyle = 'f'
    hist_vbf.drawstyle = 'HIST'
    hist_boosted.drawstyle = 'HIST'
    hist_vbf.fillstyle = 'hollow'
    hist_boosted.fillstyle = '\\'
    hist_vbf.linewidth = 2
    hist_boosted.linewidth = 2
    hist_vbf /= hist_vbf.integral()
    hist_boosted /= hist_boosted.integral()
    c = SimplePlot(xtitle=hist_vbf.xaxis.title, ytitle='Arbitrary Unit')
    c.draw('main', [vbf_hist, boosted_hist])
    leg = Legend([vbf_hist, boosted_hist],
                 textsize=15)
    leg.Draw('same')
    return c

if __name__=='__main__':
    # list of fields to plot
    fields = [
        'dR_tau1_tau2',
        'dEta_tau1_tau2',
        'tau1_pt',
        'tau2_pt',
        ]
    
    field_dict = dict([(field, VARIABLES[field]) for field in fields])
    cuts = None
    
    higgs = Higgs(2012)
    
    vbf_hists, field_scale = higgs.get_field_hist(field_dict, Category_VBF)
    boosted_hists, _ = higgs.get_field_hist(field_dict, Category_Boosted)
    
    higgs.draw_array(
        vbf_hists, Category_VBF, TARGET_REGION, 
        cuts=cuts, field_scale=field_scale)
    higgs.draw_array(
        boosted_hists, Category_Boosted, TARGET_REGION, 
        cuts=cuts, field_scale=field_scale)
    
    for field in field_dict:
        vbf_hist = vbf_hists[field]
        boosted_hist = boosted_hists[field]
        vbf_hist.title = Category_VBF.label
        boosted_hist.title = Category_Boosted.label
        vbf_hist.xaxis.title = VARIABLES[field]['root']
        boosted_hist.xaxis.title = VARIABLES[field]['root']
        pl = plot(vbf_hist, boosted_hist)
        pl.SaveAs('compare_higgs_{0}.png'.format(field))

