#!/usr/bin/env python
"""
Compare Higgs yields with and without ggF reweighting 
"""
from mva.samples import Higgs
from mva.categories.hadhad import Category_Preselection, Category_Boosted, Category_VBF, Category_Rest

categories = (Category_Preselection, Category_Boosted, Category_VBF, Category_Rest)

for year in (2011, 2012):
    print year
    higgs = Higgs(year, ggf_weight=False)
    higgs_weighted = Higgs(year)
    higgs_ggf = Higgs(year, ggf_weight=False, mode='gg')
    higgs_ggf_weighted = Higgs(year, mode='gg')

    for category in categories:
        print category.name
        print "unweighted total: {0:.2f}".format(higgs.events(category)[1].value)
        print "weighted total: {0:.2f}".format(higgs_weighted.events(category)[1].value)
        print "unweighted ggH: {0:.2f}".format(higgs_ggf.events(category)[1].value)
        print "weighted ggH: {0:.2f}".format(higgs_ggf_weighted.events(category)[1].value)
        print
