#!/usr/bin/env python
"""
"""
# python imports
import os
import pickle
import logging
from tabulate import tabulate
# ROOT/rootpy imports
from rootpy.tree import Cut
# local imports
from mva.analysis import Analysis
from mva.samples import Data
from mva.categories import Category_VBF, Category_Boosted
from mva.defaults import TARGET_REGION
from mva.plotting import draw_ratio, compare
from mva.variables import VARIABLES

log = logging.getLogger(os.path.basename(__file__))

# list of fields to plot
fields = [
    'tau1_pt',
    'tau2_pt',
    'MET_et',
    'resonance_pt',
]
field_dict = dict([(field, VARIABLES[field]) for field in fields])


#data_noTES = Data(2012, label='8 TeV Data')
data = Data(2012, name='Data Nominal', 
            label='Standard TES')
data_noTES = Data(2012, name='Data No TES shift', 
                  ntuple_path='/cluster/data12/qbuat/ntuples_hh/', 
                  student='hhskim_notesshift', 
                  label='No TES Shift')

log.info(data_noTES.events()[1].value)
log.info(data.events()[1].value)

cuts = None

# # # compare data with and without JVF cut
for category in (Category_VBF, Category_Boosted):
    data_hists, field_scale = data.get_field_hist(field_dict, category)
    data_noTES_hists, _ = data_noTES.get_field_hist(field_dict, category)
    data.draw_array(data_hists, 
                    category, 
                    TARGET_REGION, 
                    cuts=cuts,
                    field_scale=field_scale)
    data_noTES.draw_array(data_noTES_hists, 
                          category, 
                          TARGET_REGION, 
                          cuts=cuts,
                          field_scale=field_scale)
    for field in field_dict:
        # draw ratio plot
        data_hist = data_hists[field]
        data_noTES_hist = data_noTES_hists[field]
        plot = draw_ratio(data_hist, 
                          data_noTES_hist,
                          field, 
                          category, 
                          normalize=True,
                          ratio_range=(0.8, 1.2),
                          ratio_line_values=[0.9, 1, 1.1])
        for fmt in ('eps', 'png'):
            plot.SaveAs('noTES_compare_{0}_{1}.{2}'.format(category.name, field, fmt))


#     compare(data, data_noTES, field_dict,
#             category, 'data_noTES', 2012,
#             path='plots/data_noTES')

