#!/usr/bin/env python

from mva.cutflow import get_parser, make_cutflow

parser = get_parser()
args = parser.parse_args()

from higgstautau import samples as samples_db

samples = []

for signal, info in samples_db.SIGNALS['hadhad'][args.year % 1e3].items():
    for sample in info['samples']:
        samples.append((sample, sample, sample))

make_cutflow(samples, args)
