#!/usr/bin/env python

from rootpy.extern.argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('files', nargs='+')
parser.add_argument('-e', '--entries', type=int, default=100)
parser.add_argument('-s', '--select', default=None)
parser.add_argument('-o', '--order-by', default=None)
args = parser.parse_args()

from rootpy.io import root_open
import os

fields = [
    'RunNumber',
    'EventNumber',
    'MET',
    'MET_bisecting',
    'MET_phi',
    'dPhi_min_tau_MET',
    'tau_same_vertex',
    'numJets25',
    'mmc0_mass',
    'mmc1_mass',
    'mmc2_mass',
    'dR_tau1_tau2',
    'tau1_pt',
    'tau1_phi',
    'tau2_pt',
    'tau2_phi',
    'tau1_numTrack',
    'tau2_numTrack',
    'tau1_numTrack_recounted',
    'tau2_numTrack_recounted',
    'tau1_charge',
    'tau2_charge',
    'tau1_JetBDTSigMedium',
    'tau1_JetBDTSigTight',
    'tau2_JetBDTSigMedium',
    'tau2_JetBDTSigTight',
    'mc_weight',
    'tau1_matched',
    'tau2_matched',
    'tau1_efficiency_scale_factor',
    'tau2_efficiency_scale_factor',
    'tau1_fakerate_scale_factor',
    'tau2_fakerate_scale_factor',
    'tau1_trigger_scale_factor',
    'tau2_trigger_scale_factor',
]

if args.order_by is not None:
    args.order_by = args.order_by.split(',')

for filename in args.files:
    f = root_open(filename)
    t = f.higgstautauhh
    print os.path.basename(filename)
    rec = t.to_array(fields, selection=args.select)
    rec = rec[:args.entries]
    if args.order_by is not None:
        rec.sort(order=args.order_by)
    read_names = rec.dtype.names
    print ','.join(read_names)
    for row in rec:
        print ','.join(map(str, row))
    print 
    print
