#!/usr/bin/env python

from mva.samples import MC_Ztautau
from mva.defaults import TARGET_REGION
from mva.categories import Category_Preselection

from rootpy.io import root_open
from rootpy.plotting import Hist2D, Canvas
from root_numpy import fill_hist

# normal trigger correcions
ztt_mccor = MC_Ztautau(2012)
# embedding trigger corrections
ztt_ebcor = MC_Ztautau(2012, trigger=False)

# maps of pt tau1 vs pt tau2
mccor_hist = Hist2D([35, 40, 45, 50, 60, 80, 100],
                    [25, 30, 35, 40, 45, 50, 60, 80, 100],
                    name='mc_map')
ebcor_hist = mccor_hist.Clone(name='eb_map')

# get the arrays
fields = ['tau1_pt', 'tau2_pt']
mccor_arr = ztt_mccor.array(Category_Preselection, TARGET_REGION, fields)
ebcor_arr = ztt_ebcor.array(Category_Preselection, TARGET_REGION, fields)

# fill the histograms from the arrays
fill_hist(mccor_hist, mccor_arr[:,0:-1] / 1000, mccor_arr[:,-1])
fill_hist(ebcor_hist, ebcor_arr[:,0:-1] / 1000, ebcor_arr[:,-1])

# normalize
mccor_hist /= mccor_hist.integral()
ebcor_hist /= ebcor_hist.integral()

# ratio
ebmccor_hist = mccor_hist / ebcor_hist
ebmccor_hist.name = 'ebmc_weight'

# save the histograms
with root_open('embedding_corrections.root', 'RECREATE'):
    mccor_hist.Write()
    ebcor_hist.Write()
    ebmccor_hist.Write()
