#!/usr/bin/env python

from mva.samples import MC_Ztautau
from mva.defaults import TARGET_REGION
from mva.categories import Category_Preselection
from mva import log

from rootpy.io import root_open
from rootpy.plotting import Hist2D, Canvas
from root_numpy import fill_hist

output = root_open('dat/embedding_corrections.root', 'RECREATE')

for year in (2011, 2012):
    # normal trigger correcions
    ztt_mccor = MC_Ztautau(year)
    log.info(ztt_mccor.cuts())
    log.info(', '.join(ztt_mccor.weights()))

    # embedding trigger corrections
    ztt_ebcor = MC_Ztautau(year, trigger=False)
    log.info(ztt_ebcor.cuts())
    log.info(', '.join(ztt_ebcor.weights()))

    # maps of pt tau1 vs pt tau2
    mccor_hist = Hist2D([35e3, 45e3, 60e3, 1e100],
                        [25e3, 35e3, 45e3, 60e3, 1e100],
                        name='mc_map_{0}'.format(year % 1000))
    ebcor_hist = mccor_hist.Clone(name='eb_map_{0}'.format(year % 1000))

    # get the arrays
    fields = ['tau1_pt', 'tau2_pt']
    mccor_arr = ztt_mccor.array(Category_Preselection, TARGET_REGION, fields)
    ebcor_arr = ztt_ebcor.array(Category_Preselection, TARGET_REGION, fields)

    # fill the histograms from the arrays
    fill_hist(mccor_hist, mccor_arr[:,0:-1], mccor_arr[:,-1])
    fill_hist(ebcor_hist, ebcor_arr[:,0:-1], ebcor_arr[:,-1])

    # normalize
    mccor_hist /= mccor_hist.integral()
    ebcor_hist /= ebcor_hist.integral()

    # ratio
    ebmccor_hist = mccor_hist / ebcor_hist
    ebmccor_hist.name = 'ebmc_weight_{0}'.format(year % 1000)

    # save the histograms
    output.cd()
    mccor_hist.Write()
    ebcor_hist.Write()
    ebmccor_hist.Write()

output.Close()
