#!/usr/bin/env python

"""
Check for duplicate events in all trees in a ROOT file.
"""
from rootpy.extern.argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('files', nargs='+')
args = parser.parse_args()

import sys
import os
from rootpy.io import root_open
import numpy as np


def dup_idx(l):

    _, b = np.unique(l, return_inverse=True)
    return np.nonzero(np.logical_or.reduce(
                b[:, np.newaxis] == np.nonzero(np.bincount(b) > 1),
                axis=1))[0]


for i, filename in enumerate(args.files):
    print filename
    with root_open(filename) as rfile:
        for dirpath, dirs, treenames in rfile.walk(class_pattern='TTree'):
            for treename in treenames:
                tree = rfile.Get(os.path.join(dirpath, treename))
                keys = tree.to_array(['RunNumber', 'EventNumber'])
                if keys.shape != np.unique(keys).shape:
                    print "BAD  %s" % treename
                    print dup_idx(keys)
                else:
                    print "GOOD %s" % treename
    if i < len(args.files) - 1:
        # not the last file, print a blank line
        print
