#!/usr/bin/env python
"""
Find the file containing a specific event in a dataset
"""
from rootpy.extern.argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('dataset')
parser.add_argument('run')
parser.add_argument('event')
args = parser.parse_args()

import sys
import os
from rootpy.io import root_open
import logging
from higgstautau import datasets

db = datasets.Database(name='datasets_hh', verbose=False)

log = logging.getLogger('find-event')

# get the dataset from the database
dataset = db[args.dataset]

try:
    # loop over files
    for file in dataset.files:
        with root_open(file) as rfile:
            tree = rfile['tau']
            if tree.GetEntries('RunNumber=={0}&&EventNumber=={1}'.format(
                args.run, args.event)) > 0:
                print file
except KeyboardInterrupt, SystemExit:
    sys.exit(1)
