#!/usr/bin/env python

"""
Check for duplicate events in all trees in a ROOT file.
"""

import sys
import os
from rootpy.io import root_open
import numpy as np


def dup_idx(l):

    _, b = np.unique(l, return_inverse=True)
    return np.nonzero(np.logical_or.reduce(
                b[:, np.newaxis] == np.nonzero(np.bincount(b) > 1),
                axis=1))[0]


with root_open(sys.argv[1]) as rfile:
    for dirpath, dirs, treenames in rfile.walk(class_pattern='TTree'):
        for treename in treenames:
            tree = rfile.Get(os.path.join(dirpath, treename))
            keys = tree.to_array(['RunNumber', 'EventNumber'])
            if keys.shape != np.unique(keys).shape:
                print "BAD  %s" % treename
                print dup_idx(keys)
            else:
                print "GOOD %s" % treename
