#!/usr/bin/env python

from rootpy.extern.argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('--verbose', default=False, action='store_true')
parser.add_argument('--suffix', default='fixed')
parser.add_argument('--fill-empties', action='store_true', default=False)
parser.add_argument('paths', nargs='+')
args = parser.parse_args()

from statstools.fixups import fix

for path in args.paths:
    fix(path, suffix=args.suffix, verbose=args.verbose,
        fill_empties=args.fill_empties)
