#!/usr/bin/env python
# python imports
import os
import logging
import pickle
# local imports
from mva import CACHE_DIR

log = logging.getLogger(os.path.basename(__file__))

UNCERT = {}
UNCERT['gg'] = {}
UNCERT['VBF'] = {}
    
UNCERT['gg']['vbf'] = 0.054
UNCERT['gg']['boosted'] = 0.059
UNCERT['gg']['cuts_vbf_lowdr'] = 0.047
UNCERT['gg']['cuts_vbf_highdr_tight'] = 0.052
UNCERT['gg']['cuts_vbf_highdr_loose'] = 0.054
UNCERT['gg']['cuts_boosted_tight'] = 0.062 
UNCERT['gg']['cuts_boosted_loose'] = 0.056

UNCERT['VBF']['vbf'] = 0.012
UNCERT['VBF']['boosted'] = 0.01
UNCERT['VBF']['cuts_vbf_lowdr'] = 0.014
UNCERT['VBF']['cuts_vbf_highdr_tight'] = 0.01
UNCERT['VBF']['cuts_vbf_highdr_loose'] = 0.015
UNCERT['VBF']['cuts_boosted_tight'] = 0.033
UNCERT['VBF']['cuts_boosted_loose'] = 0.01

if __name__ == '__main__':

    with open(os.path.join(CACHE_DIR, 'pdf_accept_signal_uncertainty.cache'), 'w') as file:
        pickle.dump(UNCERT, file)

    for mode in sorted(UNCERT.keys()):
        for cat in sorted(UNCERT[mode].keys()):
            value = UNCERT[mode][cat]
            log.info('mode {0}, cat {1}: {2:.2f}%'.format(mode, cat, abs(value * 100)))
