#!/usr/bin/env python

from rootpy.io import root_open
from rootpy.extern.argparse import ArgumentParser
import matplotlib.pyplot as plt

parser = ArgumentParser()
parser.add_argument('--name', default='combined')
parser.add_argument('file')
args = parser.parse_args()

# default minimizer options
import ROOT
ROOT.Math.MinimizerOptions.SetDefaultStrategy(1)
ROOT.Math.MinimizerOptions.SetDefaultMinimizer('Minuit2')

rfile = root_open(args.file)
ws = rfile[args.name]
minim = ws.fit()
result = minim.save()

all_names = [
    'ATLAS_norm_HH_2011_QCD',
    'ATLAS_norm_HH_2011_Ztt',
    'ATLAS_norm_HH_2012_QCD',
    'ATLAS_norm_HH_2012_Ztt',
]

vals = []
errors = []
names = []

for name in all_names:
    value = result.floatParsFinal().find(name)
    if not value:
        continue
    vals.append(value.getVal())
    errors.append(value.getError())
    names.append(name)

# plot
fig, ax = plt.subplots(figsize=(7, 5), dpi=100)
ax.errorbar(range(len(names)), vals, yerr=errors, fmt='o')
ax.plot([-0.5, len(names) - 0.5], [1., 1.], 'r--')
ax.set_ylabel('Post-fit Normalization')
ax.set_xlim(-0.5, len(names) - 0.5)
ax.set_xticks(range(len(names)))
ax.set_xticklabels(names, rotation=45)
plt.tight_layout()
for fmt in ('eps', 'png'):
    plt.savefig('norms.{0}'.format(fmt))
