#!/usr/bin/env python
# python imports
import os
# ROOT/rootpy imports
from rootpy import ROOT
from rootpy.extern.argparse import ArgumentParser
from rootpy.stats.histfactory import measurements_from_xml, HistoSys, OverallSys
from rootpy.plotting import Hist, Legend, Graph, Canvas
# local imports
from statstools.fixups import find_measurements
from statstools import log; log = log[__name__]
from mva.templates import RatioPlot
from mva import save_canvas

parser = ArgumentParser()
parser.add_argument('paths', nargs='+')
args = parser.parse_args()

class MultipleCanvas(Canvas):
    def __init__(self, canvas_list):
        if not isinstance(canvas_list, (tuple, list)):
            raise RuntimeError('Wrong argument')
        self.Divide(len(canvas_list))            
        for ic, canv in enumerate(canvas_list):
            self.cd(ic+1)
            canv.Draw()

def draw_ratio(nom, sys_var,
               textsize=22,
               ratio_range=(0,2),
               ratio_line_values=[0.5,1,1.5],
               sys_name='syst',
               optional_label_text=None):
    """
    Draw a canvas with an Hists and its up/down systematic variations 
    and a ratio plot between the variations and the nominal
    Parameters:
    - nom: Nominal Hist -- denominator in the ratio
    - sys_var: Shifted Hists (up/down) -- numerator in the ratio
    """

    up = sys_var[0]
    do = sys_var[1]
    nom.title = 'Nominal'
    up.title = '+1 #sigma'
    do.title = '-1 #sigma'
    nom.color = 'black'
    up.color = 'red'
    do.color = 'blue'
    nom.legendstyle = 'L'
    up.legendstyle = 'L'
    do.legendstyle = 'L'
    nom.markersize = 0
    up.markersize = 0
    do.markersize = 0
    nom.linewidth = 2
    up.linewidth = 2
    do.linewidth = 2
    nom.fillstyle = 'hollow'
    up.fillstyle = 'hollow'
    do.fillstyle = 'hollow'
    nom.linestyle = 'solid'
    up.linestyle = 'dashed'
    do.linestyle = 'dashed'
    nom.drawstyle='hist E0'
    up.drawstyle='hist E0'
    do.drawstyle='hist E0'
    ratio_up = Hist.divide(up, nom, fill_value=-1)
    ratio_up.drawstyle = 'hist'
    ratio_up.color = 'red'
    ratio_do = Hist.divide(do, nom, fill_value=-1)
    ratio_do.drawstyle = 'hist'
    ratio_do.color = 'blue'

    ratio_range = (min(list(ratio_up.y())+list(ratio_do.y())),
                   max(list(ratio_up.y())+list(ratio_do.y())))

    ratio_range = ( ratio_range[0]-0.1*ratio_range[0],
                    ratio_range[1]+0.1*ratio_range[1])
                  
                   
    plot = RatioPlot(xtitle='Observable',
                     ytitle='Events',
                     ratio_title='Ratio',
                     ratio_height=0.4,
                     ratio_range=ratio_range,
                     ratio_line_values=ratio_line_values)

    plot.draw('main', [nom, up, do], ypadding=(0.3, 0.))
    plot.draw('ratio', [ratio_up, ratio_do])
    with plot.pad('main') as pad:
        # legend
        leg = Legend([nom, up, do],
                     leftmargin=0.25, topmargin=0.1,
                     margin=0.18, textsize=textsize)
        leg.Draw()
        # draw the category label
        label = ROOT.TLatex(
            pad.GetLeftMargin() + 0.04, 0.87,
            sys_name)
        label.SetNDC()
        label.SetTextFont(43)
        label.SetTextSize(textsize)
        label.Draw()
        # show p-value and chi^2
        pvalue = nom.Chi2Test(up, 'WW')
        pvalue_label = ROOT.TLatex(
            pad.GetLeftMargin() + 0.04, 0.8,
            "p-value={0:.2f}".format(pvalue))
        pvalue_label.SetNDC(True)
        pvalue_label.SetTextFont(43)
        pvalue_label.SetTextSize(textsize)
        pvalue_label.Draw()
        chi2 = nom.Chi2Test(up, 'WW CHI2/NDF')
        chi2_label = ROOT.TLatex(
            pad.GetLeftMargin() + 0.04, 0.72,
            "#frac{{#chi^{{2}}}}{{ndf}}={0:.2f}".format(chi2))
        chi2_label.SetNDC(True)
        chi2_label.SetTextFont(43)
        chi2_label.SetTextSize(textsize)
        chi2_label.Draw()
        if optional_label_text is not None:
            optional_label = ROOT.TLatex(pad.GetLeftMargin()+0.55,0.87,
                                         optional_label_text )
            optional_label.SetNDC(True)
            optional_label.SetTextFont(43)
            optional_label.SetTextSize(textsize)
            optional_label.Draw()
    return plot



def get_merged_samples(channel):
    merged_samples = []
    signal_samples = []
    for sample in channel.samples():
        if 'Signal' in sample.name:
            signal_samples.append(sample)
        else:
            merged_samples.append(sample)
    return merged_samples

def plot_np(meas):
    log.info('tot')


#------------
## MAIN DRIVER


for input_path in args.paths:
    """
    Traverse all measurements and create the syst plots
    """
    if not os.path.isdir(input_path):
        raise ValueError("input must be an existing directory")
    input_path = os.path.normpath(input_path)
    for dirpath, measurement_file in find_measurements(input_path):
        path = os.path.join(dirpath, measurement_file)
        log.info("Reading {0} ...".format(path))
        measurements = measurements_from_xml(path, cd_parent=True,
                                             collect_histograms=True,
                                             silence=False)
        for meas in measurements:
            log.info(meas.name)
            for channel in meas.channels:
                log.info(channel.name)
                for sample in channel.samples:
                    log.info(sample.name)
                    hnom = sample.hist
                    for name, osys, hsys in sample.iter_sys():
                        if isinstance(osys, OverallSys):
                            log.info('[{0}, {1}]'.format(osys.low, osys.high))
                        if isinstance(hsys, HistoSys):
                            hsys_low, hsys_high = sample.sys_hist(name)
                            plot = draw_ratio(hnom, (hsys_high, hsys_low),
                                              sys_name=name)
                            save_canvas(plot, 'plots',
                                        '{0}/shape_{1}_{2}_{3}.png'.format(meas.name,
                                                                           channel.name,
                                                                           sample.name,
                                                                           name))
                            hsys_high.Reset()
                            hsys_low.Reset()
