#!/usr/bin/env python
"""
Create variable plots
"""
from mva.cmd import get_parser

args = get_parser(actions=False).parse_args()
year = args.year

# rootpy imports
from rootpy.io import root_open
from rootpy.tree import Cut
import rootpy.plotting.utils as rootpy_utils

# local imports
from mva.plotting import draw_channel_array, uncertainty_band
from mva.systematics import get_systematics, parse_systematics
from mva.categories.hadhad import CATEGORIES
from mva.massregions import MassRegions
from mva.variables import VARIABLES, YEAR_VARIABLES, get_label
from mva.analysis import get_analysis
from mva import log

SYSTEMATICS = get_systematics(year)
args.systematics_components = parse_systematics(args.systematics_components)

mass_regions = MassRegions(
    low=args.low_mass_cut,
    high=args.high_mass_cut,
    high_sideband_in_control=args.high_sideband_in_control,
    mass_window_signal_region=False,
    #args.no_mmc,
    # not enough events to only train in signal region
    train_signal_region=False)

control_region = mass_regions.control_region
signal_region = mass_regions.signal_region
#signal_region = control_region # for creating control workspaces
train_region = mass_regions.train_region

categories = CATEGORIES[args.categories]
category_names = args.category_names
target_region = args.target_region

analysis = get_analysis(args)

output_suffix = analysis.get_suffix()

cat_defs = [args.categories]
if args.categories != 'presel':
    cat_defs.append(args.controls)

for category in analysis.iter_categories(*cat_defs, names=args.category_names):

    is_control = category.analysis_control

    cuts = Cut(args.plot_cut)

    if args.plot_expr is not None:
        VARS = {
            tuple(args.plot_expr.split(',')): {
                'title': args.plot_name,
                'range': (args.plot_min, args.plot_max),
                'bins': args.plot_bins,
                'filename': 'expr_' + args.plot_name.replace(' ', '_')}}
    else:
# 2015/08/19 DTemple: commented the following and added the "fields", "VARS" and for-loop. Note
# that the names in "fields" are taken from "variables.py", and can be anything as long as they
# exist.
        # VARS = VARIABLES
        # VARS.update(YEAR_VARIABLES[args.year])
      fields = [
# 2015/08/24 DTemple: commented out these variables from Quentin's basic plotting code
#        'jet_0_pt',
#        'jet_1_pt',
#        'n_avg_int',
#        'met_et',
#        'tau_tau_vis_mass']
# 2015/08/24 DTemple: included these variables from "variables.py" i.e. the full available list.
# The commented out variables are those that are also commented out in "variables.py".
      # 'ntrack_pv',
      # 'ntrack_nontau_pv',
        'n_avg_int',
      # 'actualIntPerXing',
###        'sum_pt',
###        'scalar_sum_pt',
###        'pt_total',
        'n_jets',
        'met_et',
        'met_etx',
        'met_ety',
        'met_phi',
###        'ditau_met_min_dphi',
###        'ditau_met_bisect',
###        'ditau_mt_lep0_met',
      # 'sphericity',
      # 'aplanarity',
###        'ditau_met_centrality',
        'tau_tau_vis_mass',
###        'ditau_coll_approx_m',
###        'ditau_mmc_mlm_m',
###        'lep_pt',
      # 'mass_tau1_tau2_jet1',
      # 'jet3_centrality',
###        'pt_ratio_lep_tau',
###        'tau_pt',
###        'tau_n_tracks',
      # 'tau1_pt',
      # 'tau2_pt',
      # 'tau1_eta',
      # 'tau2_eta',
      # 'tau1_numTrack',
      # 'tau2_numTrack',
      # 'tau1_numTrack_recounted',
      # 'tau2_numTrack_recounted',
      # 'tau1_nPi0',
      # 'tau2_nPi0',
      # 'tau_x_product',
      # 'tau_x_sum',
      # 'tau1_collinear_momentum_fraction',
      # 'tau2_collinear_momentum_fraction',
      # 'tau1_jvtxf',
      # 'tau2_jvtxf',
      # 'tau1_BDTJetScore',
      # 'tau2_BDTJetScore',
      # 'tau1_vertex_prob',
      # 'cos_theta_tau1_tau2',
      # 'theta_tau1_tau2',
###        'ditau_dr',
###        'ditau_dphi',
        'tau_tau_deta',
      # 'tau1_charge',
      # 'tau2_charge',
      # 'tau1_seedCalo_centFrac',
      # 'tau_centrality_product',
      # 'tau1_centrality',
      # 'tau2_centrality',
        'jet_1_eta',
        'jet_0_eta',
        'jet_1_pt',
        'jet_0_pt']
###        'jets_delta_eta',
###        'prod_eta_jets',
      # 'eta_product_jets_boosted',
###        'jets_visible_mass',
      # 'higgspt',
      # 'lepton_eta_centrality',
      # 'transversemass']
      VARS = {}
      for f in fields:
        VARS[f] = VARIABLES[f]

    clf = None
    if not is_control:
# 2015/08/19 DTemple: redefined "clf" as otherwise gets hung up on incorrect BDT training info
#        clf = analysis.get_clf(category, load=True, transform=True)
        clf = None
    figs = draw_channel_array(
        analysis,
        vars=VARS,
        mass=125,
        mode='combined',
        signal_scale=(
            50 if is_control or 'preselection' in category.name else 20),
        plot_label=(
            'Signal Region' if not is_control and
            not ('preselection' in category.name) else None),
        category=category,
        region=target_region,
        #systematics_components=args.systematics_components,
        output_formats=args.output_formats,
        weighted=not args.no_weight,
        plots=args.plots,
        output_suffix=output_suffix,
        unblind=args.unblind,  # or is_control,
        cuts=cuts,
        show_ratio=args.show_ratio,
# 2015/08/19 DTemple: added "include_signal"
        include_signal=False
        #clf=clf,
        #min_score=0.5924344731341187,
        #no_data=args.no_data,
        #top_label="Fakes Model: {0}".format(analysis.fakes_region),
        )
