#!/usr/bin/env python

from rootpy.io import root_open
from rootpy.extern.argparse import ArgumentParser
import matplotlib.pyplot as plt

parser = ArgumentParser()
parser.add_argument('--name', default='combined')
parser.add_argument('file')
args = parser.parse_args()

# default minimizer options
import ROOT
ROOT.Math.MinimizerOptions.SetDefaultStrategy(1)
ROOT.Math.MinimizerOptions.SetDefaultMinimizer('Minuit2')

rfile = root_open(args.file)
ws = rfile[args.name]
minim = ws.fit()
result = minim.save()

all_names = [
    'ATLAS_norm_HH_2011_QCD',
    'ATLAS_norm_HH_2011_Ztt',
    'ATLAS_norm_HH_2012_QCD',
    'ATLAS_norm_HH_2012_Ztt',
]

vals = []
errors = []
names = []

for name in all_names:
    value = result.floatParsFinal().find(name)
    if not value:
        continue
    vals.append(value.getVal())
    errors.append(value.getError())
    names.append(name.replace('ATLAS_norm_', '').replace('_', ' '))

# plot
fig, ax = plt.subplots(figsize=(7, 5), dpi=100)
ax.errorbar(vals, range(len(names)), xerr=errors, fmt='o')
for x, y, error in zip(vals, range(len(names)), errors):
    plt.annotate('${0:.2f} \pm {1:.2f}$'.format(x, error),
                 textcoords='offset points', xytext=(0, 15),
                 bbox=dict(boxstyle='square,pad=0.5', fc='white', alpha=0.5),
                 xy=(x, y), ha='center', va='bottom')
ax.plot([1., 1.], [-0.5, len(names) - 0.5], 'r--')
ax.set_xlabel('Post-fit Normalization')
ax.set_ylim(-0.5, len(names) - 0.5)
ax.set_yticks(range(len(names)))
ax.set_yticklabels(names)
plt.tight_layout()
for fmt in ('eps', 'png'):
    plt.savefig('norms.{0}'.format(fmt))
