#!/usr/bin/env python

import sys
import os
from rootpy.io import root_open as ropen

with ropen(sys.argv[1]) as f:
    for path, dirs, objects in f.walk(class_pattern="TH1*"):
        for hist_name in objects:
            hist = f.Get(os.path.join(path, hist_name))
            print hist.name
            for i, limit in enumerate(hist):
                print hist.xaxis.GetBinLabel(i + 1), limit
            print
