#!/usr/bin/env python
# python imports
import os
import logging
import pickle
# local imports
from mva import CACHE_DIR

log = logging.getLogger(os.path.basename(__file__))

UNCERT = {}
UNCERT['gg'] = {}
UNCERT['VBF'] = {}
    
UNCERT['gg']['vbf'] = 0.01
UNCERT['gg']['boosted'] = 0.01
UNCERT['gg']['cuts_vbf_lowdr'] = 0.006
UNCERT['gg']['cuts_vbf_highdr_tight'] = 0.45 
UNCERT['gg']['cuts_vbf_highdr_loose'] = 0.17
UNCERT['gg']['cuts_boosted_tight'] = 0.01 
UNCERT['gg']['cuts_boosted_loose'] = 0.16 

UNCERT['VBF']['vbf'] = 0.08
UNCERT['VBF']['boosted'] = 0.05
UNCERT['VBF']['cuts_vbf_lowdr'] = 0.11
UNCERT['VBF']['cuts_vbf_highdr_tight'] = 0.08
UNCERT['VBF']['cuts_vbf_highdr_loose'] = 0.03
UNCERT['VBF']['cuts_boosted_tight'] = 0.09
UNCERT['VBF']['cuts_boosted_loose'] = 0.02

if __name__ == '__main__':

    with open(os.path.join(CACHE_DIR, 'ps_signal_uncertainty.cache'), 'w') as file:
        pickle.dump(UNCERT, file)

    for mode in sorted(UNCERT.keys()):
        for cat in sorted(UNCERT[mode].keys()):
            value = UNCERT[mode][cat]
            log.info('mode {0}, cat {1}: {2:.2f}%'.format(mode, cat, abs(value * 100)))
