#!/usr/bin/env python

from rootpy.extern.argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('--verbose', action='store_true', default=False)
parser.add_argument('file')
parser.add_argument('workspace')
args = parser.parse_args()

from statstools import get_limit_workspace
from rootpy.io import root_open

with root_open(args.file) as f:
    if args.workspace not in f:
        f.ls()
    else:
        h = get_limit_workspace(
            f[args.workspace], verbose=args.verbose)
        print list(h)
