#!/usr/bin/env python
from mva.cmd import get_parser

args = get_parser(actions=False).parse_args()

from mva.analysis import get_analysis
from mva.categories.hadhad import Category_Preselection
from tabulate import tabulate
ana = get_analysis(args)
ana.normalize(Category_Preselection)


headers = [ana.ztautau.name, ana.qcd.name, ana.others.name, ana.data.name]
print headers
yields= []
yields.append([
    ana.ztautau.events(Category_Preselection, args.target_region)[1].value,
    ana.qcd.events(Category_Preselection, args.target_region)[1].value,
    ana.others.events(Category_Preselection, args.target_region)[1].value,
    ana.data.events(Category_Preselection, args.target_region)[1].value,
])

print tabulate(yields, headers=headers)

# print "Ztautau"
# print ana.ztautau.events(Category_Preselection)[1].value

# print "Others"
# print ana.others.events(Category_Preselection)[1].value

# print "QCD"
# print ana.qcd.events(Category_Preselection)[1].value

