#!/usr/bin/env python

from rootpy.tree import Cut
from mva.analysis import Analysis
from mva import MMC_MASS
from mva.samples import Higgs
from mva.categories.hadhad import (Category_Preselection, Category_Rest,
                                   Category_Boosted, Category_VBF)

ztt_cr = Cut('70 < {0} < 110'.format(MMC_MASS)) & Cut('resonance_pt > 120000') & Cut('dR_tau1_tau2 < 1.5')
fmt = '{a[1].value:.3f} +/- {a[1].error:.3f}'

def display(hist):
    return fmt.format(a=hist)


year = 2012
category = Category_Preselection

ana_isol = Analysis(year=year, target_region='OS_ISOL').normalize(Category_Preselection)
ana = Analysis(year=year, target_region='OS').normalize(Category_Preselection)
ztt_isol = ana_isol.ztautau
ztt = ana.ztautau
qcd_isol = ana_isol.qcd
qcd = ana.qcd
others = ana.others
data = ana.data
higgs = Higgs(year=year)
data_isol_events = data.events(category, 'OS_ISOL', cuts=ztt_cr)
qcd_isol_events = qcd_isol.events(category, 'OS_ISOL', cuts=ztt_cr)
ztt_isol_events = ztt_isol.events(category, 'OS_ISOL', cuts=ztt_cr)
others_isol_events = others.events(category, 'OS_ISOL', cuts=ztt_cr)
higgs_isol_events = higgs.events(category, 'OS_ISOL', cuts=ztt_cr)

data_events = data.events(category, 'OS', cuts=ztt_cr)
qcd_events = qcd.events(category, 'OS', cuts=ztt_cr)
ztt_events = ztt.events(category, 'OS', cuts=ztt_cr)
others_events = others.events(category, 'OS', cuts=ztt_cr)
higgs_events = higgs.events(category, 'OS', cuts=ztt_cr)

print year
print 'OS'
print category.name, display(data_events), display(ztt_events / data_events), display(qcd_events / data_events), display(others_events / data_events), display(higgs_events / data_events)
print 'OS ISOL'
print category.name, display(data_isol_events), display(ztt_isol_events / data_isol_events), display(qcd_isol_events / data_isol_events), display(others_isol_events / data_isol_events), display(higgs_isol_events / data_isol_events)
print display((ztt_isol_events / (data_isol_events - qcd_isol_events - others_isol_events)) / (ztt_events / (data_events - qcd_events - others_events)))
print
