#!/usr/bin/env python

from ROOT import TLorentzVector
from random import gauss
import math

a = TLorentzVector()
b = TLorentzVector()

for i in xrange(10000):
    a.SetPxPyPzE(gauss(0, 5), gauss(0, 5), 0, 1);
    b.SetPxPyPzE(gauss(0, 5), gauss(0, 5), 0, 1);
    assert(round(abs(a.DeltaPhi(b)) - (math.pi - math.fabs(math.fabs(a.Phi() - b.Phi()) - math.pi)), 7) == 0)
