#!/usr/bin/env python
from rootpy.extern.argparse import ArgumentParser

#parser = ArgumentParser()
#parser.add_argument('file1')
#parser.add_argument('file2')
#parser.add_argument('tree')
#args = parser.parse_args()

from rootpy.io import root_open
import os

file1 = root_open('ntuples/prod/hhskim/hhskim.root')
file2 = root_open('ntuples/prod/hhskim_CONF_nov_2013/hhskim.root')

for dirpath, dirs, treenames in file1.walk(class_pattern='TTree'):
    for treename in treenames:
        treepath = os.path.join(dirpath, treename)
        if treepath not in file2:
            continue
        print treename

        tree1 = file1[treepath]
        tree2 = file2[treepath]

        selection1 = '((((((dEta_jets>2.0)&&((jet1_pt>50000)&&(jet2_pt>30000)))&&(resonance_pt>40000))&&((((((((trigger)&&(tau1_pt>35000))&&(tau2_pt>25000))&&(MET_et>20000))&&(mmc1_mass>0))&&((0.8<dR_tau1_tau2)&&(dR_tau1_tau2<2.8)))&&(tau_same_vertex))&&(MET_bisecting||(dPhi_min_tau_MET<1.570796))))&&(dEta_tau1_tau2<1.5))&&(((tau1_charge*tau2_charge)==-1)&&(((tau1_numTrack_recounted==1)||(tau1_numTrack_recounted==3))&&((tau2_numTrack_recounted==1)||(tau2_numTrack_recounted==3)))))'
        selection2 = '((((((dEta_jets>2.0)&&((jet1_pt>50000)&&(jet2_pt>30000)))&&(resonance_pt>40000))&&((((((((taus_pass)&&(tau1_pt>35000))&&(tau2_pt>25000))&&(MET_et>20000))&&(mmc1_mass>0))&&((0.8<dR_tau1_tau2)&&(dR_tau1_tau2<2.8)))&&(tau_same_vertex))&&(MET_bisecting||(dPhi_min_tau_MET<1.570796))))&&(dEta_tau1_tau2<1.5))&&(((tau1_charge*tau2_charge)==-1)&&(((tau1_numTrack_recounted==1)||(tau1_numTrack_recounted==3))&&((tau2_numTrack_recounted==1)||(tau2_numTrack_recounted==3)))))'

        print tree1.GetEntries(selection1)
        print tree2.GetEntries(selection2)
