#!/usr/bin/env python

from mva.cutflow import get_parser, make_cutflow

parser = get_parser()
parser.add_argument('--grl', default=None)
parser.add_argument('--runs', type=int, nargs='*')
args = parser.parse_args()

data_name = 'data%d-JetTauEtmiss' % (args.year % 1e3)

if args.grl:
    from goodruns import GRL
    grl = GRL(args.grl)
    samples = [(run, run, "{0}-{1}".format(data_name, run)) for run in grl]
elif args.runs:
    samples = [(run, run, "{0}-{1}".format(data_name, run)) for run in args.runs]
else:
    from pyAMI.client import AMIClient
    from pyAMI.query import get_periods, get_runs

    periods = get_periods(AMIClient(), year=args.year)
    # only keep top-level periods (skip M)
    periods = [p for p in periods if
               len(p.name) == 1 and p.status == 'frozen'][:-1]
    
    samples = [(p.name, p.name, "{0}-{1}".format(data_name, p.name))
               for p in periods]

make_cutflow(samples, args)
