#!/usr/bin/env python

import os
import sys
import re
from glob import glob
import shutil

inputfile = os.path.normpath(sys.argv[1])
xmldir = os.path.normpath(sys.argv[2])
xmloutdir = xmldir + '_render'
xmlfiles = glob('%s/*.xml' % xmldir)
resultsdir = '%s_results' % xmldir

if os.path.exists(xmloutdir):
    shutil.rmtree(xmloutdir)
os.mkdir(xmloutdir)

for xmlfilename in xmlfiles:
    fin = open(xmlfilename, 'r')
    fout = open(os.path.join(xmloutdir, os.path.basename(xmlfilename)), 'w')
    for line in fin:
        line = line.replace(xmldir, xmloutdir)
        line = line.replace(
            '<StatError Activate="True"  InputFile=""  HistoName=""  HistoPath=""  />',
            '<StatError Activate="True" />')
        line = line.replace('InputFile=""', 'InputFile="%s"' % inputfile)
        line = line.replace('<Combination OutputFilePrefix="" >',
                            '<Combination OutputFilePrefix="%s/hist2workspace" >' %
                            resultsdir)
        line = re.sub('\w+=""', '', line)
        line = re.sub('\s+/>', ' />', line)
        line = re.sub('"\s\s+(\S)', r'" \1', line)
        line = line.replace('<Input>./workspaces/', '<Input>./')
        # HistFactory bug:
        line = line.replace('<ParamSetting Const="True"></ParamSetting>', '')
        # found floats
        line = re.sub(r'\d*\.\d{4,}',
                      lambda x: str(round(float(x.group()), 3)), line)
        fout.write(line)
    fin.close()
    fout.close()

rootsys = os.getenv('ROOTSYS')
shutil.copy('%s/etc/HistFactorySchema.dtd' % rootsys, xmloutdir)
